name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diff-store: true
          use-flakehub: false
          diagnostic-endpoint: ""
      - name: Run Nix Build
        run: |
          nix build .#demo --print-build-logs
      - uses: actions/upload-artifact@main
        id: upload-artifact
        with:
          path: result
          name: demo
      - uses: actions/attest-build-provenance@main
        with:
          subject-name: demo
          subject-digest: sha256:${{ steps.upload-artifact.outputs.artifact-digest }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      deployments: write
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@main
        with:
          name: demo
          path: result

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./result/ --project-name=rune-ls-wasm-demo
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
